#!/bin/bash

# Load modules and environment
module load anaconda3
source activate /gpfs/exfel/exp/SQS/202302/p004098/usr/env

# This variable stops complaints about CUDA not being found by mpirun
#export MPI_MCA_btl_openib_warn_no_device_params_found=0
export OMPI_MCA_mpi_cuda_support=0

# Add dragonfly stuff to modulepath 
export MODULEPATH=/home/ayyerkar/.local/modules:$MODULEPATH

# CUDA module for cupy (need to be on GPU node)
module load cuda/10.2
